SELECT "TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" 
FROM   TEST_KYLIN_FACT 
WHERE  (CASE "TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" 
	WHEN 'Auction' THEN '111' 
	WHEN 'FP-GTC' THEN '222' 
	ELSE '999' END) = '111'
GROUP BY "TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" 