SELECT "TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" 
FROM   TEST_KYLIN_FACT 
WHERE  ((CASE WHEN ("TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" = 'Auction') THEN 'Auction1' ELSE "TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" END) = 'Auction1')
GROUP BY "TEST_KYLIN_FACT"."LSTG_FORMAT_NAME" 