--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

SELECT COUNT(1)
FROM TEST_KYLIN_FACT
INNER JOIN TEST_ORDER AS TEST_ORDER
ON TEST_KYLIN_FACT.ORDER_ID = TEST_ORDER.ORDER_ID
WHERE CAL_DT > '1992-01-01'
AND (
SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'A'
OR SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'B'
OR SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'C'
OR SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'D'
OR SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'E'
OR SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'F'
OR 'G' = SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1)
OR SUBSTRING(LSTG_FORMAT_NAME FROM 1 FOR 1) = 'H'
)
GROUP BY CAL_DT
