--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
select a.LSTG_FORMAT_NAME,a.LEAF_CATEG_ID,c.SITE_ID
from (
select LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID,count(distinct SELLER_ID) as type_SELLER_ID
from TEST_KYLIN_FACT
where CAL_DT = '2012-01-01'
group by LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID
)a
inner join (
select LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID,count(distinct SELLER_ID) as type_SELLER_ID
from TEST_KYLIN_FACT
where CAL_DT = '2012-01-01'
group by LSTG_FORMAT_NAME,LEAF_CATEG_ID,LSTG_SITE_ID
)b
on a.LSTG_FORMAT_NAME=b.LSTG_FORMAT_NAME
and a.LEAF_CATEG_ID=b.LEAF_CATEG_ID
left join TEST_CATEGORY_GROUPINGS as c
on a.LSTG_SITE_ID=c.SITE_ID