--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT
    "NAME"
,   COUNT("TRANS_ID")   AS  "C1"
FROM
    "DEFAULT"."TEST_KYLIN_FACT"
INNER JOIN
    "DEFAULT"."TEST_ACCOUNT" ON  "TEST_KYLIN_FACT"."SELLER_ID"   =   "TEST_ACCOUNT"."ACCOUNT_ID"
INNER JOIN
    EDW.TEST_CAL_DT AS  TEST_CAL_DT ON TEST_ACCOUNT.CAL_DT =   TEST_CAL_DT.CAL_DT
INNER JOIN
    TEST_CATEGORY_GROUPINGS ON TEST_ACCOUNT.LEAF_CATEG_ID  =  TEST_CATEGORY_GROUPINGS.LEAF_CATEG_ID AND TEST_ACCOUNT.LSTG_SITE_ID   =   TEST_CATEGORY_GROUPINGS.SITE_ID
INNER JOIN
    EDW.TEST_SITES  AS  TEST_SITES ON TEST_ACCOUNT.LSTG_SITE_ID   =   TEST_SITES.SITE_ID
INNER JOIN
    "DEFAULT"."TEST_COUNTRY" ON  "TEST_ACCOUNT"."ACCOUNT_COUNTRY"    =   "TEST_COUNTRY"."COUNTRY"
GROUP BY
    "NAME"