--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
select CAL_DT,
count('aaa') COUNT0, max('aaa') MAX0,
count('aaa') over() COUNT1, max('aaa') over() MAX1, first_value('fff') over() FFF0,
TIMESTAMPDIFF(MONTH, DATE'2012-01-01',test_kylin_fact.cal_dt) * count(1) DIFF1,
TIMESTAMPDIFF(MONTH, TIMESTAMP'2012-01-01 10:01:01',test_kylin_fact.cal_dt) * count(1) over() DIFF2,
max(TIMESTAMPADD(SQL_TSI_DAY, 1, TIMESTAMP'1970-01-01 10:01:01')) MAXTIME,
max(TIMESTAMPADD(SQL_TSI_DAY, 1, DATE'1970-01-01')) MAXDATE,
max(TIMESTAMPADD(SQL_TSI_DAY, 1, TIMESTAMP'1970-01-01 10:01:01')) over() MAXTIME1,
max(TIMESTAMPADD(SQL_TSI_DAY, 1, DATE'1970-01-01')) over() MAXDATE1
from TEST_KYLIN_FACT
where CAL_DT > DATE'2013-12-30'
group by CAL_DT
order by TIMESTAMPADD(SQL_TSI_DAY,1, TIMESTAMP'1970-01-01 10:01:01'),
TIMESTAMPADD(SQL_TSI_DAY,1, DATE'1970-01-01')