--sql618,sql745,sql746
-- divide float
select
    "CALCS"."DATETIME0",
    HOUR (CAST ("CALCS"."DATETIME0" AS TIMESTAMP)),
    HOUR (CAST ("CALCS"."DATETIME0" AS TIMESTAMP)) / 24.0
FROM "TDVT"."CALCS"  "CALCS"
Group By
   "CALCS"."DATETIME0",
   HOUR (CAST ("CALCS"."DATETIME0" AS TIMESTAMP)),
   HOUR (CAST ("CALCS"."DATETIME0" AS TIMESTAMP)) / 24.0