--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

select "TEST_CATEGORY_GROUPINGS"."ADULT_CATEG_YN" as "ADULT_CATEG_YN",
  "TEST_CATEGORY_GROUPINGS"."BSNS_VRTCL_NAME" as "BSNS_VRTCL_NAME",
  "TEST_CATEGORY_GROUPINGS"."CATEG_BUSN_MGR" as "CATEG_BUSN_MGR",
  "TEST_CATEGORY_GROUPINGS"."CATEG_BUSN_UNIT" as "CATEG_BUSN_UNIT",
  "TEST_CATEGORY_GROUPINGS"."CATEG_FLAGS" as "CATEG_FLAGS",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL2_ID" as "CATEG_LVLC_ID",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL2_NAME" as "CATEG_LVLC_NAME",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL3_ID" as "CATEG_LVLD_ID",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL3_NAME" as "CATEG_LVLD_NAME",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL4_ID" as "CATEG_LVLE_ID",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL4_NAME" as "CATEG_LVLE_NAME",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL5_ID" as "CATEG_LVLF_ID",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL5_NAME" as "CATEG_LVLF_NAME",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL6_ID" as "CATEG_LVLG_ID",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL6_NAME" as "CATEG_LVLG_NAME",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL7_ID" as "CATEG_LVLH_ID",
  "TEST_CATEGORY_GROUPINGS"."CATEG_LVL7_NAME" as "CATEG_LVLH_NAME",
--"TEST_CATEGORY_GROUPINGS"."CRE_DATE" AS "CRE_DATE",
 -- "TEST_CATEGORY_GROUPINGS"."CRE_USER" AS "CRE_USER",
  "TEST_CATEGORY_GROUPINGS"."DOMAIN_ID" as "DOMAIN_ID",
  "TEST_CATEGORY_GROUPINGS"."GCS_ID" as "GCS_ID",
  "TEST_CATEGORY_GROUPINGS"."LEAF_CATEG_ID" as "LEAF_CATEG_ID",
  "TEST_CATEGORY_GROUPINGS"."LEAF_CATEG_NAME" as "LEAF_CATEG_NAME",
  "TEST_CATEGORY_GROUPINGS"."META_CATEG_ID" as "META_CATEG_ID",
  "TEST_CATEGORY_GROUPINGS"."META_CATEG_NAME" as "META_CATEG_NAME",
  "TEST_CATEGORY_GROUPINGS"."MOVE_TO" as "MOVE_TO",
  1 as "Number_of_Records",
  "TEST_CATEGORY_GROUPINGS"."REGN_CATEG" as "REGN_CATEG",
  "TEST_CATEGORY_GROUPINGS"."SAP_CATEGORY_ID" as "SAP_CATEGORY_ID",
  "TEST_CATEGORY_GROUPINGS"."SITE_ID" as "SITE_ID",
  "TEST_CATEGORY_GROUPINGS"."SRC_ID" as "SRC_ID",
  "TEST_CATEGORY_GROUPINGS"."UPD_DATE" as "UPD_DATE",
  "TEST_CATEGORY_GROUPINGS"."UPD_USER" as "UPD_USER",
  "TEST_CATEGORY_GROUPINGS"."USER_DEFINED_FIELD1" as "USER_DEFINED_FIELDB",
  "TEST_CATEGORY_GROUPINGS"."USER_DEFINED_FIELD3" as "USER_DEFINED_FIELDD",
  "TEST_CATEGORY_GROUPINGS"."USER_DEFINED_FIELD5" as "USER_DEFINED_FIELDF",
  "TEST_CATEGORY_GROUPINGS"."VCS_ID" as "VCS_ID"
from "TEST_CATEGORY_GROUPINGS" "TEST_CATEGORY_GROUPINGS"
LIMIT 10000
