-- KE-14446 sum case when with count distinct
SELECT
COUNT(1),
SUM(CASE WHEN LSTG_FORMAT_NAME =  'ABIN' THEN PRICE ELSE 2 END),
COUNT(DISTINCT SELLER_ID),
COUNT(DISTINCT ACCOUNT_ID),
SUM(ACCOUNT_ID),
ACCOUNT_COUNTRY,
LSTG_FORMAT_NAME
FROM TEST_KYLIN_FACT LEFT JOIN TEST_ACCOUNT
ON SELLER_ID = ACCOUNT_ID
GROUP BY LSTG_FORMAT_NAME, ACCOUNT_COUNTRY

