--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
SELECT
"TEST_KYLIN_FACT"."TRANS_ID" as "TEST_KYLIN_FACT_TRANS_ID",
 TRUNCATE(PRICE, 0),
 TRUNCATE(sum(PRICE),-1),
TRUNCATE(sum(PRICE),0),
TRUNCATE(sum(PRICE),10),
TRUNCATE(sum(PRICE),1+1),
TRUNCATE(sum(PRICE)*1.00001,-1),
TRUNCATE(sum(PRICE)-1.00001,0),
TRUNCATE(sum(PRICE)/3.3,10),
TRUNCATE(CAST(sum(PRICE) AS double),10),
TRUNCATE(cast(sum(PRICE) as float),0),
TRUNCATE(cast(TRANS_ID as smallint),0),
TRUNCATE(cast(TRANS_ID as tinyint),0),
TRUNCATE(cast(sum(PRICE) as float),2),
TRUNCATE(cast(sum(PRICE) as double),-1),
TRUNCATE(cast(sum(PRICE) as double),0),
TRUNCATE(cast(sum(PRICE) as double),2)
FROM
"DEFAULT"."TEST_KYLIN_FACT" as "TEST_KYLIN_FACT"
WHERE
1 = 1
and TRANS_ID < 100
group by "TEST_KYLIN_FACT"."TRANS_ID"
,PRICE