SELECT * FROM (SELECT (SELECT COUNT(DISTINCT O_TOTALPRICE) AS O_TOTALPRICE FROM TPCH.ORDERS) AS O_TOTALPRICE
FROM TPCH.ORDERS
GROUP BY O_TOTALPRICE) T1 INNER JOIN (SELECT O_TOTALPRICE FROM TPCH.ORDERS) T2 ON T1.O_TOTALPRICE = T2.O_TOTALPRICE

