SELECT "GEOX_BYR_CNTRY_LVL_LKP"."GLBL_RPRT_CNTRY_LVL1_NM" AS "none_GLBL_RPRT_CNTRY_LVLB_NM_nk",   "GEOX_TRANS_MTRC_SD"."LSTG_CNDTN_DESC" AS "none_LSTG_CNDTN_DESC_nk",   "DW_SITES"."SITE_NAME" AS "none_SITE_NAME_nk",   SUM("GEOX_TRANS_MTRC_SD"."GMV_USD_AMT") AS "sum_GMV_USD_AMT_ok" 
FROM "GEOX_TRANS_MTRC_SD"   
LEFT JOIN "GEOX_DW_CAL_DT" ON ("GEOX_TRANS_MTRC_SD"."CAL_DT" = "GEOX_DW_CAL_DT"."CAL_DT")   
LEFT JOIN "DW_SITES" ON ("GEOX_TRANS_MTRC_SD"."ITEM_SITE_ID" = "DW_SITES"."SITE_ID")   
LEFT JOIN "GEOX_BYR_CNTRY_LVL_LKP" ON ("GEOX_TRANS_MTRC_SD"."BYR_CNTRY_ID" = "GEOX_BYR_CNTRY_LVL_LKP"."BUYER_CNTRY_ID")   
WHERE (("GEOX_DW_CAL_DT"."CAL_DT" >= {d '2014-08-18'}) AND ("GEOX_DW_CAL_DT"."CAL_DT" <= {d '2014-09-01'})) 
GROUP BY "GEOX_BYR_CNTRY_LVL_LKP"."GLBL_RPRT_CNTRY_LVL1_NM",   "GEOX_TRANS_MTRC_SD"."LSTG_CNDTN_DESC",   "DW_SITES"."SITE_NAME"