--
-- Copyright (C) 2016 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

SELECT  COUNT(*) AS CNT,sum(LFNAME1) as sum_p
FROM
(
select  PRICE as LFNAME1, TEST_COUNT_DISTINCT_BITMAP as bitmap1 from TEST_KYLIN_FACT
) as t1
INNER JOIN
(
select  PRICE as LFNAME2, TEST_COUNT_DISTINCT_BITMAP as bitmap2 from TEST_KYLIN_FACT
) as t2
on
(((t1.LFNAME1 = t2.LFNAME2) OR ((t1.LFNAME1 is null) AND (t2.LFNAME2 is null)))
and (t1.bitmap1 = t2.bitmap2 OR ((t1.bitmap1 is null) AND (t2.bitmap2 is null))))

