--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
-- equi join with non-equi joins
SELECT TEST_ACC.LEAF_CATEG_NAME, count(TEST_ACC.ACCOUNT_COUNTRY), sum(TEST_KYLIN_FACT.ITEM_COUNT)
FROM TEST_KYLIN_FACT
LEFT JOIN
(
  select TEST_ACCOUNT.ACCOUNT_ID as ACCOUNT_ID, TEST_ACCOUNT.ACCOUNT_COUNTRY as ACCOUNT_COUNTRY, TEST_CATEGORY_GROUPINGS.LEAF_CATEG_NAME as LEAF_CATEG_NAME
  FROM TEST_ACCOUNT
  LEFT JOIN TEST_CATEGORY_GROUPINGS
  ON TEST_CATEGORY_GROUPINGS.SITE_ID > 2
) TEST_ACC
ON TEST_KYLIN_FACT.SELLER_ID = TEST_ACC.ACCOUNT_ID
GROUP BY TEST_ACC.LEAF_CATEG_NAME
ORDER BY 1,2,3
LIMIT 10000