--
-- Copyright (C) 2020 Kyligence Inc. All rights reserved.
--
-- http://kyligence.io
--
-- This software is the confidential and proprietary information of
-- Kyligence Inc. ("Confidential Information"). You shall not disclose
-- such Confidential Information and shall use it only in accordance
-- with the terms of the license agreement you entered into with
-- Kyligence Inc.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-- A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-- OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

SELECT KYLIN_SALES.PRICE,
KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME,
KYLIN_SALES.LSTG_FORMAT_NAME,
count(1),
count(DISTINCT KYLIN_SALES.PRICE + 1),
count(DISTINCT substring(KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME, 0, 4)),
count(DISTINCT CONCAT(KYLIN_SALES.LSTG_FORMAT_NAME, KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME))
FROM TEST_KYLIN_FACT as KYLIN_SALES
JOIN TEST_CATEGORY_GROUPINGS KYLIN_CATEGORY_GROUPINGS ON KYLIN_SALES.LEAF_CATEG_ID = KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_ID
GROUP BY KYLIN_SALES.PRICE,
KYLIN_CATEGORY_GROUPINGS.LEAF_CATEG_NAME,
KYLIN_SALES.LSTG_FORMAT_NAME